# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./"
  command = "npm run build"
  [build.environment]
    GIT_LFS_ENABLED = "1"
[[headers]]
  for="/*"
  [headers.values]
    Link = '''
      </css/styles/index.css>; rel=preload; as=style, \
      </css/js/index.js>; rel=preload; as=script, \
      </img/icons.svg>; rel=preload; as=image
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    Content-Security-Policy = '''
      default-src 'self';
      base-uri 'self';
      img-src 'self' https://secure.gravatar.com/avatar/ https://i.imgur.com/;
      script-src 'self';
      style-src 'self';
      connect-src 'self';
      worker-src: 'self';
      font-src 'self';
      media-src 'none';
      child-src 'self';
      object-src: 'none';
      manifest-src 'self';
      form-action 'self';
      reflected-xss block;
      block-all-mixed-content;
      upgrade-insecure-requests;
      disown-opener;'''
# [[redirects]]
  # from = ""
  # to = ""
